I edited constriants file
MIT-Emerging-Talent/ET6-foundations-group-32 pull request #12
Opened 2024-12-30 14:35 UTC by marshar007007

I have updated the constraints file. Please, review the file.

2024-12-30 19:48 UTC, Ammmoe commented on collaboration/constraints.md
> +  Limitations of WhatsApp and Slack for certain tasks like file sharing or code reviews.
Could you be more specific about how the communication tools pose as external constraints?

2024-12-30 20:06 UTC, Ammmoe requested changes
Overall, it's clear to me that you put a lot of effort into writing this readme file. The contents are solid. However, I'd like to request two changes for this pull request:  

1. I do not quite understand (subjective to me) how the communication tools pose as external constraints. So I'd like to make a request to update the line to a more specific version.
2. Please put colons (**`:`**) after each subtitle for better read. For example, "**Time Zones`:`** Group members are located in ... convenient meeting times".

> Note: First, you may edit the file in VSCode, then do the usual steps (git add, git commit, and git push) and the changes will be automatically updated to this pull request.

2024-12-30 20:24 UTC, Ammmoe commented on collaboration/constraints.md
> +  Limitations of WhatsApp and Slack for certain tasks like file sharing or code reviews.
But maybe it'd be more clear if you put an example like: `difficulty in sharing video files of a member reviewing the code or explaining some topics`.

2024-12-31 15:21 UTC, nico1103 commented on collaboration/constraints.md
> +   only if needed.
A small typo: one-on-one

2024-12-31 15:26 UTC, nico1103 requested changes
A small typo: one-on-one

2025-01-01 03:41 UTC, marshar007007 commented on collaboration/constraints.md
> +  Limitations of WhatsApp and Slack for certain tasks like file sharing or code reviews.
thanks for the comment, I will make changes based on review

2025-01-01 03:42 UTC, marshar007007 commented on collaboration/constraints.md
> +   only if needed.
thank u for your comments!

2025-01-01 03:55 UTC, marshar007007 commented on collaboration/constraints.md
> +  Limitations of WhatsApp and Slack for certain tasks like file sharing or code reviews.
@Ammmoe Final draft of constraints is updated, can u check again, please!

2025-01-01 07:51 UTC, Ammmoe commented on .vscode/settings.json
> +      "source.organizeImports.ruff": "explicit"
Hi! Could you please set these back to `true` ? 
For example, they should be:
> "source.fixAll.ruff": true,
> "source.organizeImports.ruff": true

I'm sorry if I edit them by myself, then I'll become the last committer and will not be able to merge the pull request.

2025-01-01 07:53 UTC, Ammmoe commented on collaboration/constraints.md
> +    since they have to use VPN to use these communication channels.
The last sentence is not a complete sentence so maybe you can make it complete or maybe you can leave the sentence out.

2025-01-01 07:55 UTC, Ammmoe commented on collaboration/constraints.md
> +- **Program Requirements** :
Sorry for nitpicking at this point but you do not have to put `space` after the subtitle.
For example: `**Program Requirements**: The CDS program's ...`

2025-01-01 08:00 UTC, Ammmoe requested changes
Hi @marshar007007 !

Thank you so much for making changes according to my comments.
I'd like to request some small changes before I proceed with merging the pull request.

So sorry if it seems like nitpicking at this point but think of it like practicing reviewing and practicing push and pull requests for us.

Thanks!!

2025-01-01 13:32 UTC, Ammmoe approved these changes
Looks Great! Thank you for writing the constraints readme file and all the CI checks pass @marshar007007!

2025-01-01 13:41 UTC, nico1103 approved these changes

2025-01-01 13:42 UTC, merged